[general]
live_config_reload = true
working_directory = "C:\\Users\\Administrator"
[terminal]
shell = "C:\\Program Files\\PowerShell\\7-preview\\pwsh.exe"
[font]
size = 12.0
normal.family = "Maple Mono NF CN"
bold.family = "Maple Mono NF CN"
italic.family = "Maple Mono NF CN"
bold_italic.family = "Maple Mono NF CN"
